from enum import Enum


class EventType(Enum):
    CROSS_UP = "CROSS_UP"
    CROSS_DOWN = "CROSS_DOWN"
    GAP_CROSS_UP = "GAP_CROSS_UP"
    GAP_CROSS_DOWN = "GAP_CROSS_DOWN"
    SUPPORT_TEST = "SUPPORT_TEST"
    RESISTANCE_TEST = "RESISTANCE_TEST"
    SUPPORT_BOUNCE = "SUPPORT_BOUNCE"
    RESISTANCE_REJECTION = "RESISTANCE_REJECTION"
    BREACH_CONFIRMED = "BREACH_CONFIRMED"
    BREACH_CONFIRMED_NO_ALPHA = "BREACH_CONFIRMED_NO_ALPHA"
    REST_ON_ANGLE = "REST_ON_ANGLE"
    TARGET_HIT = "TARGET_HIT"
    TARGET_FAILED = "TARGET_FAILED"
    FAN_VALIDATED = "FAN_VALIDATED"
    ZONE_CHANGE = "ZONE_CHANGE"
    FAN_DEACTIVATED = "FAN_DEACTIVATED"
